name: CI

on:
  pull_request:
    branches: ["main"]
  
  push:
    branches:
      - "renovate/**"

# Prevent duplicate runs if Renovate falls back to creating a PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

# We are using OpenID Connect to authenticate with Azure with secret.
# https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-azure
permissions:
  id-token: write
  contents: read

jobs:
  main:
    runs-on: [idp]
    environment: ci
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Authenticate to Azure DevOps artifacts
        uses: workleap/wl-reusable-workflows/az-artifact-authenticate@main
        with:
          feed-url: ${{ secrets.NUGET_GSOFTDEV_FEED_URL }}
          variables: ${{ toJSON(vars) }}

      - run: ./Build.ps1
        shell: pwsh
        env:
          NUGET_SOURCE: ${{ secrets.NUGET_GSOFTDEV_FEED_URL }}

  linearb:
    needs: [main]
    uses: workleap/wl-reusable-workflows/.github/workflows/linearb-deployment.yml@main
    with:
      environment: development
    permissions:
      id-token: write
      contents: read
